### ISSUE TITLE
hyclone_server crashes if HPREFIX is not set

### ISSUE THREAD

**Issue by diversys** [trungnt2910/hyclone#10]
Apart from crashing I think build_hprefix.sh should warn if HPREFIX is not set and show how to set one.

```
./build_hprefix.sh
...
Setup HyClone prefix
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
./build_hprefix.sh: line 151: 419377 Aborted                
 (core dumped) $HYCLONE_INSTALL_PREFIX/bin/hyclone_server
```

**Comment by trungnt2910** [comment]
Thanks for the report. `build_hprefix.sh` automatically infers the `HPREFIX` from existing variables but `hyclone_server` and `haiku_loader` doesn't.

I've now updated both of them to determine `$HPREFIX` similar to how `build_hprefix.sh`.
