### ISSUE TITLE
build_hprefix.sh not able to complete

### ISSUE THREAD

**Issue by pcklee123** [trungnt2910/hyclone#14]
Hi, I am trying to follow the instructions. I am using ubuntu on WSL2. I get the following error when I try to do the step with ./build_hprefix.sh

Keeping installed package: zstd-1.5.2-3-x86_64.hpkg
Installing package: gettext_libintl-0.21.1-3-x86_64.hpkg
terminate called after throwing an instance of 'LibHpkg::HpkException'
  what():  unable to setup the hpkg file extractor: unable to establish the file type
./build_hprefix.sh: line 151: 175026 Aborted                 $HYCLONE_INSTALL_PREFIX/bin/hyclone_server

**Comment by trungnt2910** [comment]
Can you run `./hyclone_server` on the same `$HPREFIX`?

If the problem persists, can you attach a `gdb` session and generate a stack trace?

Seems like some HPKG format error.

**Comment by pcklee123** [comment]
Thanks.  I found that  gettext_libintl-0.21.1-3-x86_64.hpkg is only 153 bytes in ~/.hprefix/boot/system/packages.
 If I try to download it by wget https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/gettext_libintl-0.21.1-3-x86_64.hpkg
I get a 404 error.
Its only for this hpkg, all others downloaded fine.
I also tried to download older versions of this file but get 404 error.

**Comment by pcklee123** [comment]
removing thet gettext file and run ./build_hprefix.sh again. The download gets a 153 byte file.
gcc_syslibs already exists
Downloading gettext_libintl-0.21.1-3-x86_64.hpkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    294      0 --:--:-- --:--:-- --:--:--   294
graphite2 already exists
gzip already exists
harfbuzz already exists

**Comment by pcklee123** [comment]
If I open the gettext file it is actually html. saying 404 not found error.

**Comment by trungnt2910** [comment]
This is strange. When I visited the package website on the official HaikuDepot page (https://depot.haiku-os.org/#!/pkg/gettext_libintl/haikuports/haikuports_x86_64/0/21/1/-/3/x86_64?bcguid=bc185-GHRI) and clicked `Download package 'hpkg' file`, the download also failed with 404 not found.

This seems like a problem on the HaikuDepot server.

**Comment by Begasus** [comment]
gettext has been given a revbump yesterday, the depot isn't updated (site): try this:
 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/gettext-0.21.1-4-x86_64.hpkg

**Comment by trungnt2910** [comment]
⬆️ We can use this as a workaround, manually download this to the `$HPREFIX/boot/system/packages` before somebody fixes this problem and/or HaikuDepot updates itself.

**Comment by trungnt2910** [comment]
This is a HaikuDepot bug, nothing we can do on the HyClone project side.
